management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /docs
    url: /docs/openapi.yaml

ditto:
  security:
    api-key: ${API_KEY}
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}
