spring:
  application:
    name: ditto-admin
  profiles:
    active: local
    include:
      - db
  thymeleaf:
    cache: false

server:
  port: 8081
  shutdown: graceful

ditto:
  oauth:
    kakao:
      client-id: test-client-id
      client-secret: ""
      redirect-uri: http://localhost:8081/oauth/kakao/callback
