object DependencyVersions {
    const val KOTLIN = "1.9.25"
    const val SPRING_BOOT = "3.5.11"
    const val SPRING_DEPENDENCY_MANAGEMENT = "1.1.7"
    const val H2 = "2.3.232"
    const val MYSQL_CONNECTOR = "8.3.0"
    const val QUERYDSL = "7.1"
    const val KOTEST = "5.9.1"
    const val KOTEST_SPRING = "1.3.0"
    const val MOCKK = "1.13.13"
    const val SPRING_MOCKK = "4.0.2"
    const val KOTLIN_LOGGING = "7.0.3"
    const val LOGSTASH_LOGBACK = "8.0"
    const val MICROMETER_PROMETHEUS = "1.14.4"
    const val SPRINGDOC_OPENAPI = "2.7.0"
    const val JJWT = "0.12.6"
    const val JACKSON = "2.18.2"
    const val COROUTINES = "1.9.0"
    const val RESTDOCS_API_SPEC = "0.19.4"
}

object Dependencies {
    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib"
    const val SPRING_BOOT_STARTER = "org.springframework.boot:spring-boot-starter"
    const val SPRING_BOOT_STARTER_WEB = "org.springframework.boot:spring-boot-starter-web"
    const val SPRING_BOOT_STARTER_DATA_JPA = "org.springframework.boot:spring-boot-starter-data-jpa"
    const val SPRING_BOOT_STARTER_VALIDATION = "org.springframework.boot:spring-boot-starter-validation"
    const val SPRING_BOOT_STARTER_SECURITY = "org.springframework.boot:spring-boot-starter-security"
    const val SPRING_BOOT_STARTER_ACTUATOR = "org.springframework.boot:spring-boot-starter-actuator"
    const val SPRING_BOOT_STARTER_AOP = "org.springframework.boot:spring-boot-starter-aop"
    const val SPRING_BOOT_STARTER_TEST = "org.springframework.boot:spring-boot-starter-test"
    const val H2 = "com.h2database:h2:${DependencyVersions.H2}"
    const val MYSQL_CONNECTOR = "com.mysql:mysql-connector-j:${DependencyVersions.MYSQL_CONNECTOR}"
    const val JACKSON_MODULE_KOTLIN = "com.fasterxml.jackson.module:jackson-module-kotlin:${DependencyVersions.JACKSON}"
    const val JACKSON_DATATYPE_JSR310 = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${DependencyVersions.JACKSON}"
    const val MICROMETER_PROMETHEUS = "io.micrometer:micrometer-registry-prometheus:${DependencyVersions.MICROMETER_PROMETHEUS}"
    const val KOTLIN_LOGGING = "io.github.oshai:kotlin-logging-jvm:${DependencyVersions.KOTLIN_LOGGING}"
    const val LOGSTASH_LOGBACK = "net.logstash.logback:logstash-logback-encoder:${DependencyVersions.LOGSTASH_LOGBACK}"
    const val KOTEST_RUNNER = "io.kotest:kotest-runner-junit5:${DependencyVersions.KOTEST}"
    const val KOTEST_ASSERTIONS = "io.kotest:kotest-assertions-core:${DependencyVersions.KOTEST}"
    const val KOTEST_PROPERTY = "io.kotest:kotest-property:${DependencyVersions.KOTEST}"
    const val KOTEST_SPRING = "io.kotest.extensions:kotest-extensions-spring:${DependencyVersions.KOTEST_SPRING}"
    const val MOCKK = "io.mockk:mockk:${DependencyVersions.MOCKK}"
    const val SPRING_MOCKK = "com.ninja-squad:springmockk:${DependencyVersions.SPRING_MOCKK}"
    const val SPRINGDOC_OPENAPI = "org.springdoc:springdoc-openapi-starter-webmvc-ui:${DependencyVersions.SPRINGDOC_OPENAPI}"
    const val JJWT_API = "io.jsonwebtoken:jjwt-api:${DependencyVersions.JJWT}"
    const val JJWT_IMPL = "io.jsonwebtoken:jjwt-impl:${DependencyVersions.JJWT}"
    const val JJWT_JACKSON = "io.jsonwebtoken:jjwt-jackson:${DependencyVersions.JJWT}"
    const val COROUTINES_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${DependencyVersions.COROUTINES}"
    const val COROUTINES_REACTOR = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor:${DependencyVersions.COROUTINES}"
    const val QUERYDSL_JPA = "io.github.openfeign.querydsl:querydsl-jpa:${DependencyVersions.QUERYDSL}"
    const val QUERYDSL_APT = "io.github.openfeign.querydsl:querydsl-apt:${DependencyVersions.QUERYDSL}:jpa"
    const val SPRING_RESTDOCS_MOCKMVC = "org.springframework.restdocs:spring-restdocs-mockmvc"
    const val RESTDOCS_API_SPEC_MOCKMVC = "com.epages:restdocs-api-spec-mockmvc:${DependencyVersions.RESTDOCS_API_SPEC}"
}
